apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ecom-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: ecom.rules
    rules:
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total[5m]) * 60 * 5 > 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} is crash looping"
        description: "Pod {{ $labels.pod }} has restarted more than once in 5 minutes"
    - alert: HighCPU
      expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High CPU on {{ $labels.instance }}"
        description: "CPU usage is above 80% for 5 minutes"
    - alert: NodeNotReady
      expr: kube_node_status_condition{condition="Ready",status="true"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Node {{ $labels.node }} is not ready"
        description: "Node has been not ready for more than 1 minute"
